### ISSUE TITLE
npm start Error

### ISSUE THREAD

**Issue by kimsijin33** [brandiqa/sp-mall-park-wrld#2] opened 2021-02-09 09:52 UTC
below error occured when I was "npm start" command excute 

How can I fix it?

=========================
$npm start 

> mallmap@1.0.0 start
> parcel src/index.html

sh: 1: parcel: not found
npm ERR! code 127
npm ERR! path /home/anaconda/sp-mall-park-wrld-master
npm ERR! command failed
npm ERR! command sh -c parcel src/index.html

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-09T09_50_41_415Z-debug.log

**Comment by brandiqa** [comment] 2021-02-09 14:11
This is a duplicate of #1

**Closed as completed by brandiqa** 2021-02-09 14:11 UTC
